# Generated by Django 5.1.3 on 2024-11-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ava',
            field=models.ImageField(null=True, upload_to='images/users/avas/'),
        ),
    ]
